title: Justin Kiggins
description: neuroscience via engineering via music

url: http://www.justinkiggins.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Blog
   url: /blog
 - title: Contact
   url: /contact

social:
   github: neuromusic
   twitter: neuromusic
   linkedin: justinkiggins
   email: justin.kiggins@gmail.com

google_analytics: "UA-344915-7"
feedburner: http://feeds.feedburner.com/justinkiggins-blog


# RSS
name: Justin Kiggins