title: Justin Kiggins
description: neuroscience via engineering via music

url: http://127.0.0.1:4000
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact

social:
   github: neuromusic
   twitter: neuromusic
   email: justin.kiggins@gmail.com

google_analytics: "UA-344915-7"


# RSS
name: Justin Kiggins